version: "3.7"
services:
  frontend-service:
  # image: jenkins-ansible:5000/frontend:${BUILD_NUMBER}
    image: ansible-jenkins:5000/frontend:${BUILD_NUMBER}
    deploy:
      replicas: 2
    container_name: frontend
    build: FrontEnd/
    environment:
    - USERNAME=${USERNAME}
    - PASSWORD=${PASSWORD}
    - MYSQL_URL=${MYSQL_URL}
    - MYSQL_DB=${MYSQL_DB}
    - MYSQL_DB_TEST=${MYSQL_DB_TEST}
    - SECRET_KEY=${SECRET_KEY}
